// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.gao.proto;

public interface StudentResponseListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.gao.proto.StudentResponseList)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.gao.proto.StudentResponse studentResponse = 1;</code>
     */
    java.util.List<StudentResponse>
    getStudentResponseList();

    /**
     * <code>repeated .com.gao.proto.StudentResponse studentResponse = 1;</code>
     */
    StudentResponse getStudentResponse(int index);

    /**
     * <code>repeated .com.gao.proto.StudentResponse studentResponse = 1;</code>
     */
    int getStudentResponseCount();

    /**
     * <code>repeated .com.gao.proto.StudentResponse studentResponse = 1;</code>
     */
    java.util.List<? extends StudentResponseOrBuilder>
    getStudentResponseOrBuilderList();

    /**
     * <code>repeated .com.gao.proto.StudentResponse studentResponse = 1;</code>
     */
    StudentResponseOrBuilder getStudentResponseOrBuilder(
            int index);
}
